name: my_voice_tutor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  firebase_core: ^2.0.0
  cloud_functions: ^4.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.16.0
  google_sign_in: ^6.3.0
  firebase_storage: ^11.6.5
  uuid: ^4.5.1
  path: ^1.9.1
  file_picker: ^9.0.2
  path_provider: ^2.1.5
  logger: ^2.5.0
  flutter_tts: ^4.2.2
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e

# dependency_overrides: 
#   firebase_core: ^3.12.1
#   firebase_auth: ^5.5.1
#   firebase_storage: ^12.3.7
#   cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5

flutter:
  generate: true
  uses-material-design: true