// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA7WFMltBIEYhpqa9ykawyocGtQ17dXsU',
    appId: '1:412604211422:web:372203d9b0ba8de9cd224f',
    messagingSenderId: '412604211422',
    projectId: 'my-voice-tutor',
    authDomain: 'my-voice-tutor.firebaseapp.com',
    storageBucket: 'my-voice-tutor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwjpXLOvAA0ReJ-Vn_vU3hGUbwij5PEis',
    appId: '1:412604211422:android:33cfcf0443e7c5e4cd224f',
    messagingSenderId: '412604211422',
    projectId: 'my-voice-tutor',
    storageBucket: 'my-voice-tutor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMUYBiG40XcJTZBxSOE-YCGW5PNViesRY',
    appId: '1:412604211422:ios:a63dab80d290c53fcd224f',
    messagingSenderId: '412604211422',
    projectId: 'my-voice-tutor',
    storageBucket: 'my-voice-tutor.firebasestorage.app',
    iosBundleId: 'com.example.myVoiceTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMUYBiG40XcJTZBxSOE-YCGW5PNViesRY',
    appId: '1:412604211422:ios:a63dab80d290c53fcd224f',
    messagingSenderId: '412604211422',
    projectId: 'my-voice-tutor',
    storageBucket: 'my-voice-tutor.firebasestorage.app',
    iosBundleId: 'com.example.myVoiceTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA7WFMltBIEYhpqa9ykawyocGtQ17dXsU',
    appId: '1:412604211422:web:fbe9aef1d8dcac45cd224f',
    messagingSenderId: '412604211422',
    projectId: 'my-voice-tutor',
    authDomain: 'my-voice-tutor.firebaseapp.com',
    storageBucket: 'my-voice-tutor.firebasestorage.app',
  );

}